[
  {
    id: 1,
    name: "Brent and Nancy",
    members: [
      { id: 0, name: "Brent", rsvp: "undecided" },
      { id: 1, name: "Nancy", rsvp: "undecided" },
    ],
  },
  {
    id: 2,
    name: "Troy and Mary",
    members: [
      { id: 3, name: "Troy", rsvp: "undecided" },
      { id: 4, name: "Mary", rsvp: "undecided" },
      { id: 5, name: "Ranchel", rsvp: "undecided" },
      { id: 6, name: "Scott", rsvp: "undecided" },
      { id: 7, name: "Jessica", rsvp: "undecided" },
      { id: 8, name: "Becca", rsvp: "undecided", plusOne: "undecided" },
      { id: 9, name: "Isaac", rsvp: "undecided", plusOne: "undecided" },
      { id: 10, name: "Zach", rsvp: "undecided" },
      { id: 11, name: "Lizzy", rsvp: "undecided" },
      { id: 12, name: "Abby", rsvp: "undecided", plusOne: "undecided" },
      { id: 13, name: "Levi", rsvp: "undecided" },
      { id: 14, name: "Brinley", rsvp: "undecided" },
    ],
  },
  {
    id: 3,
    name: "Ron and Faith",
    members: [
      { id: 15, name: "Ron", rsvp: "undecided" },
      { id: 16, name: "Faith", rsvp: "undecided" },
      { id: 17, name: "David", rsvp: "undecided" },
      { id: 18, name: "Savanna", rsvp: "undecided" },
      { id: 19, name: "Zealand", rsvp: "undecided" },
      { id: 20, name: "Kendall", rsvp: "undecided" },
      { id: 21, name: "Katy", rsvp: "undecided" },
      { id: 22, name: "Stetson", rsvp: "undecided" },
      { id: 23, name: "Marnie", rsvp: "undecided" },
      { id: 24, name: "Caleb", rsvp: "undecided" },
      { id: 25, name: "Evaline", rsvp: "undecided" },
      { id: 26, name: "Samuel", rsvp: "undecided" },
      { id: 27, name: "Alyssa", rsvp: "undecided", plusOne: "undecided" },
      { id: 28, name: "Emily", rsvp: "undecided", plusOne: "undecided" },
      { id: 29, name: "Kate", rsvp: "undecided", plusOne: "undecided" },
      { id: 30, name: "Jaron", rsvp: "undecided", plusOne: "undecided" },
    ],
  },
  {
    id: 4,
    name: "Sandy and Joe",
    members: [
      { id: 31, name: "Sandy", rsvp: "undecided" },
      { id: 32, name: "Joe", rsvp: "undecided" },
      { id: 33, name: "Austin", rsvp: "undecided" },
      { id: 34, name: "Courtney", rsvp: "undecided" },
      { id: 35, name: "Grayson", rsvp: "undecided" },
      { id: 36, name: "Brinley", rsvp: "undecided" },
      { id: 37, name: "Jackson", rsvp: "undecided" },
      { id: 38, name: "Maddy", rsvp: "undecided", plusOne: "undecided" },
      { id: 39, name: "Chris", rsvp: "undecided", plusOne: "undecided" },
      { id: 40, name: "Parker", rsvp: "undecided", plusOne: "undecided" },
    ],
  },
  {
    id: 5,
    name: "Larry and Annette",
    members: [
      { id: 41, name: "Larry", rsvp: "undecided" },
      { id: 42, name: "Anet", rsvp: "undecided" },
      { id: 43, name: "Taylor", rsvp: "undecided" },
      { id: 44, name: "Caeden", rsvp: "undecided" },
      { id: 45, name: "Eli", rsvp: "undecided" },
      { id: 46, name: "Cam", rsvp: "undecided" },
      { id: 47, name: "Baby", rsvp: "undecided" },
      { id: 48, name: "James", rsvp: "undecided" },
      { id: 49, name: "Mia", rsvp: "undecided" },
      { id: 50, name: "Jenna", rsvp: "undecided", plusOne: "undecided" },
      { id: 51, name: "Brooke", rsvp: "undecided", plusOne: "undecided" },
    ],
  },
  {
    id: 6,
    name: "Cheri and Ryan",
    members: [
      { id: 52, name: "Cheri", rsvp: "undecided" },
      { id: 53, name: "Ryan", rsvp: "undecided" },
      { id: 54, name: "TJ", rsvp: "undecided", plusOne: "undecided" },
      { id: 55, name: "Andrew", rsvp: "undecided", plusOne: "undecided" },
      { id: 56, name: "Ashley", rsvp: "undecided" },
      { id: 57, name: "Blake", rsvp: "undecided" },
      { id: 58, name: "Logan", rsvp: "undecided" },
      { id: 59, name: "Ty", rsvp: "undecided" },
      { id: 60, name: "Mark", rsvp: "undecided", plusOne: "undecided" },
      { id: 61, name: "Jacob", rsvp: "undecided" },
      { id: 62, name: "Maddy", rsvp: "undecided" },
    ],
  },
  {
    id: 7,
    name: "Randy and Jaqui",
    members: [
      { id: 63, name: "Randy", rsvp: "undecided" },
      { id: 64, name: "Jaqui", rsvp: "undecided" },
      { id: 65, name: "Kaella", rsvp: "undecided" },
      { id: 66, name: "Shawn", rsvp: "undecided" },
      { id: 67, name: "Emitt", rsvp: "undecided" },
      { id: 68, name: "Avery", rsvp: "undecided" },
      { id: 69, name: "Theo", rsvp: "undecided" },
      { id: 70, name: "Owen", rsvp: "undecided" },
      { id: 71, name: "Morgan", rsvp: "undecided", plusOne: "undecided" },
      { id: 72, name: "Eli", rsvp: "undecided", plusOne: "undecided" },
      { id: 73, name: "Savanna", rsvp: "undecided", plusOne: "undecided" },
    ],
  },
];
